name: pytorch_sac
channels:
  - defaults
dependencies:
  - python=3.6
  - pytorch
  - cudatoolkit=9.2
  - absl-py
  - pyparsing
  - pip:
    - termcolor
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - git+https://github.com/facebookresearch/hydra@0.11_branch